apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: fe258209-b514-40fe-8ec3-b451b5178854
    subject: custom_litmus
    workflow_id: 92729852-4dba-4c81-bc3a-623fb2feebdc
    workflows.argoproj.io/controller-instanceid: fe258209-b514-40fe-8ec3-b451b5178854
  name: custom-1670486893
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: kubelet-service-kill-enk
        template: kubelet-service-kill-enk
  - container:
      args:
      - kubectl apply -f /tmp/kubelet-service-kill-enk.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: kubelet-service-kill-enk
        path: /tmp/kubelet-service-kill-enk.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Kills the kubelet service on the application node to check the resiliency.
            kind: ChaosExperiment
            metadata:
              name: kubelet-service-kill
              labels:
                name: kubelet-service-kill
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.12.0
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: litmuschaos/go-runner:2.12.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name kubelet-service-kill
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: NODE_LABEL
                    value: ""
                  - name: LIB_IMAGE
                    value: ubuntu:16.04
                  - name: TARGET_NODE
                    value: ""
                labels:
                  name: kubelet-service-kill
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/service-kill: "true"
                  app.kubernetes.io/version: 2.12.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-kubelet-service-kill-enk.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: kubelet-service-kill-enk
        path: /tmp/chaosengine-kubelet-service-kill-enk.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: kubelet-service-kill-enk
              labels:
                workflow_run_id: "{{workflow.uid}}"
            spec:
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              experiments:
                - name: kubelet-service-kill
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "300"
                        - name: TARGET_NODE
                          value: gke-hcllink-default-pool-7d131db4-6ea5
                      nodeSelector:
                        chaos: "true"
                      tolerations:
                        - effect: NoSchedule
                          key: chaos
                          operator: Equal
                          value: "true"
                    probe: []
              components:
                runner:
                  nodeSelector:
                    chaos: "true"
    metadata:
      labels:
        weight: "10"
    name: kubelet-service-kill-enk
    outputs: {}
status:
  finishedAt: null
  startedAt: null
