apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 61dd221f-824e-4f36-acff-a28fa3f55724
    subject: custom-scenario-1670777953_litmus
    workflow_id: 96aec270-a262-4edb-bd72-2279f3663cca
    workflows.argoproj.io/controller-instanceid: 61dd221f-824e-4f36-acff-a28fa3f55724
  name: custom-scenario-1670777953
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: node-drain-fs2
        template: node-drain-fs2
  - container:
      args:
      - kubectl apply -f /tmp/node-drain-fs2.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-drain-fs2
        path: /tmp/node-drain-fs2.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Drain the node where application pod is scheduled
            kind: ChaosExperiment
            metadata:
              name: node-drain
              labels:
                name: node-drain
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.12.0
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                      - pods/eviction
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - daemonsets
                    verbs:
                      - list
                      - get
                      - delete
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                      - patch
                image: litmuschaos/go-runner:2.12.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name node-drain
                command:
                  - /bin/bash
                env:
                  - name: TARGET_NODE
                    value: ""
                  - name: NODE_LABEL
                    value: ""
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: LIB
                    value: litmus
                  - name: RAMP_TIME
                    value: ""
                labels:
                  name: node-drain
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.12.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-node-drain-fs2.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.12.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-drain-fs2
        path: /tmp/chaosengine-node-drain-fs2.yaml
        raw:
          data: "apiVersion: litmuschaos.io/v1alpha1\nkind: ChaosEngine\nmetadata:\n
            \ namespace: \"{{workflow.parameters.adminModeNamespace}}\"\n  generateName:
            node-drain-fs2\n  labels:\n    workflow_run_id: \"{{workflow.uid}}\"\nspec:\n
            \ engineState: active\n  auxiliaryAppInfo: \"\"\n  chaosServiceAccount:
            litmus-admin\n  experiments:\n    - name: node-drain\n      spec:\n        components:\n
            \         env:\n            - name: TOTAL_CHAOS_DURATION\n              value:
            \"300\"\n            - name: TARGET_NODE\n              value: \"gke-hcllink-default-pool-7d131db4-lzxj\"\n
            \       probe:\n          - name: DX-Availability-SOT-probe\n            type:
            cmdProbe\n            mode: SOT\n            runProperties:\n              probeTimeout:
            20\n              retry: 3\n              interval: 20\n              stopOnFailure:
            false\n            cmdProbe/inputs:\n              command: ./dxscript.sh
            34.86.107.240 wpsadmin DAM test testdesc\n              source:\n                image:
            gcr.io/blackjack-209019/services/hcldx/hclhelmdx:latest\n                hostNetwork:
            false\n              comparator:\n                type: string\n                criteria:
            contains\n                value: \"409\"\n          - name: DX-Availability-Continuous-probe\n
            \           type: cmdProbe\n            mode: Continuous\n            runProperties:\n
            \             probeTimeout: 30\n              retry: 8\n              interval:
            30\n              stopOnFailure: false\n            httpProbe/inputs:
            {}\n            cmdProbe/inputs:\n              command: ./dxscript.sh
            34.86.107.240 wpsadmin DAM test testdesc\n              source:\n                image:
            gcr.io/blackjack-209019/services/hcldx/hclhelmdx:latest\n                hostNetwork:
            false\n              comparator:\n                type: string\n                criteria:
            contains\n                value: \"409\"\n          - name: DX-Availability-EOT-probe\n
            \           type: cmdProbe\n            mode: EOT\n            runProperties:\n
            \             probeTimeout: 20\n              retry: 3\n              interval:
            20\n              stopOnFailure: false\n            httpProbe/inputs:
            {}\n            cmdProbe/inputs:\n              command: ./dxscript.sh
            34.86.107.240 wpsadmin DAM test testdesc\n              source:\n                image:
            gcr.io/blackjack-209019/services/hcldx/hclhelmdx:latest\n                hostNetwork:
            false\n              comparator:\n                type: string\n                criteria:
            contains\n                value: \"409\"\n  annotationCheck: \"false\"
            \             \n"
    metadata:
      labels:
        weight: "10"
    name: node-drain-fs2
    outputs: {}
status:
  finishedAt: null
  startedAt: null
