apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: e40bb87d-7d75-49ee-9afd-7f11e8f4181a
    subject: custom-workflow-1662402789_litmus
    workflow_id: 7215c887-05b5-4cf3-890f-bf38c349b21c
    workflows.argoproj.io/controller-instanceid: e40bb87d-7d75-49ee-9afd-7f11e8f4181a
  name: custom-workflow-1662402789
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: TARGET_PODS
      value: ""
    - name: APP_NAME_SPACE
      value: prod-hwa
    - name: APP_LABEL
      value: app.kubernetes.io/instance=prod-hwa
    - name: APP_KIND
      value: ""
    - name: SEQUENCE
      value: parallel
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  nodeSelector:
    noproduct: "true"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete-txz
        template: pod-delete-txz
  - container:
      args:
      - kubectl apply -f /tmp/pod-delete-txz.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.9.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete-txz
        path: /tmp/pod-delete-txz.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
              labels:
                name: pod-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.9.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.9.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "15"
                  - name: RAMP_TIME
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "5"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: TARGET_PODS
                    value: "{{workflow.parameters.TARGET_PODS}}"
                  - name: NODE_LABEL
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.9.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-delete-txz.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.9.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete-txz
        path: /tmp/chaosengine-pod-delete-txz.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-delete-txz
              labels:
                instance_id: c66fb028-3b13-46cf-9a81-441d2df5858a
                context: pod-delete-txz_k1litmus
                workflow_name: custom-workflow-1662402789
            spec:
              appinfo:
                appns: "{{workflow.parameters.APP_NAME_SPACE}}"
                applabel: "{{workflow.parameters.APP_LABEL}}"
                appkind: "{{workflow.parameters.APP_KIND}}"
              engineState: active
              chaosServiceAccount: litmus-admin
              components:
                runner:
                  nodeSelector:
                    noproduct: "true"
                  tolerations:
                    - key: noproduct
                      operator: Equal
                      value: "true"
                      effect: NoSchedule
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      nodeSelector:
                        noproduct: "true"
                      tolerations:
                        - key: noproduct
                          operator: Equal
                          value: "true"
                          effect: NoSchedule
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "300"
                        - name: CHAOS_INTERVAL
                          value: "300"
                        - name: FORCE
                          value: "false"
                        - name: PODS_AFFECTED_PERC
                          value: "100"
                        - name: SEQUENCE
                          value: "{{workflow.parameters.SEQUENCE}}"
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete-txz
    outputs: {}
  tolerations:
  - effect: NoSchedule
    key: noproduct
    operator: Equal
    value: "true"
status:
  finishedAt: null
  startedAt: null
