apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 5dc21284-8e18-426b-917a-90df31d12dea
    subject: custom-workflow-1659110559_litmus
    workflow_id: b0743d57-509a-4e28-88dd-93ffc31bf72a
    workflows.argoproj.io/controller-instanceid: 5dc21284-8e18-426b-917a-90df31d12dea
  name: custom-workflow-1659110559
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: TARGET_PODS
      value: ""
    - name: APP_NAME_SPACE
      value: usuite
    - name: APP_KIND
      value: deployment
    - name: APP_LABEL
      value: app.kubernetes.io/name=unicalink-client
    - name: DOMAIN
      value: unicalink-client.unica1.chaos.sofythree.com
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  nodeSelector:
    noproduct: "true"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete
        template: pod-delete
  - container:
      args:
      - kubectl apply -f /tmp/pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
              labels:
                name: pod-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.7.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - apps
                      - apps.openshift.io
                      - argoproj.io
                      - batch
                      - litmuschaos.io
                    resources:
                      - deployments
                      - jobs
                      - pods
                      - pods/log
                      - replicationcontrollers
                      - deployments
                      - statefulsets
                      - daemonsets
                      - replicasets
                      - deploymentconfigs
                      - rollouts
                      - pods/exec
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                      - deletecollection
                image: litmuschaos/go-runner:2.7.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "50"
                  - name: RAMP_TIME
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: PODS_AFFECTED_PERC
                    value: "100"
                  - name: LIB
                    value: litmus
                  - name: TARGET_PODS
                    value: "{{workflow.parameters.TARGET_PODS}}"
                  - name: SEQUENCE
                    value: parallel
                  - name: APP_LABEL
                    value: "{{workflow.parameters.APP_LABEL}}"
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.7.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-delete
              labels:
                instance_id: 51a4d2bd-ab00-4bc4-8075-2ab7b3b976ed
                context: pod-delete_litmus
                workflow_name: custom-workflow-1659110559
            spec:
              appinfo:
                appns: "{{workflow.parameters.APP_NAME_SPACE}}"
                applabel: "{{workflow.parameters.APP_LABEL}}"
                appkind: "{{workflow.parameters.APP_KIND}}"
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              components:
                runner:
                  nodeSelector:
                    noproduct: "true"
                  tolerations:
                    - key: noproduct
                      operator: Equal
                      value: "true"
                      effect: NoSchedule
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      nodeSelector:
                        noproduct: "true"
                      tolerations:
                        - key: noproduct
                          operator: Equal
                          value: "true"
                          effect: NoSchedule
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "100"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                      statusCheckTimeouts:
                        delay: 2
                        timeout: 2700
                    probe:
                      - name: platform-homepage-availability-start
                        type: httpProbe
                        mode: SOT
                        runProperties:
                          probeTimeout: 1
                          retry: 1
                          interval: 1
                          probePollingInterval: 1
                          stopOnFailure: false
                        httpProbe/inputs:
                          url: https://{{workflow.parameters.DOMAIN}}/login
                          insecureSkipVerify: true
                          responseTimeout: 1000
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
                      - name: platform-homepage-availability-continuous
                        type: httpProbe
                        mode: Continuous
                        runProperties:
                          probeTimeout: 1
                          retry: 1
                          interval: 1
                          probePollingInterval: 1
                          stopOnFailure: false
                        httpProbe/inputs:
                          url: https://{{workflow.parameters.DOMAIN}}/login
                          insecureSkipVerify: true
                          responseTimeout: 1000
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
                      - name: platform-homepage-availability-end
                        type: httpProbe
                        mode: EOT
                        runProperties:
                          probeTimeout: 1
                          retry: 1
                          interval: 1
                          probePollingInterval: 1
                          stopOnFailure: false
                        httpProbe/inputs:
                          url: https://{{workflow.parameters.DOMAIN}}/login
                          insecureSkipVerify: true
                          responseTimeout: 1000
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
  tolerations:
  - effect: NoSchedule
    key: noproduct
    operator: Equal
    value: "true"
status:
  finishedAt: null
  startedAt: null
