apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: a52233cf-0973-44cc-bb9f-591b7738e570
    subject: custom-chaos-workflow_litmus
    workflow_id: 83ff8813-2364-47d3-8480-0cf16c9b0cf7
    workflows.argoproj.io/controller-instanceid: a52233cf-0973-44cc-bb9f-591b7738e570
  name: custom-chaos-workflow-1662705982
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-dns-error-xzi
        template: pod-dns-error-xzi
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-dns-error-xzi.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.9.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-dns-error-xzi
        path: /tmp/pod-dns-error-xzi.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Pod DNS Error injects dns failure/error in target pod containers
            kind: ChaosExperiment
            metadata:
              name: pod-dns-error
              labels:
                name: pod-dns-error
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.9.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.9.0
                args:
                  - -c
                  - ./experiments -name pod-dns-error
                command:
                  - /bin/bash
                env:
                  - name: TARGET_CONTAINER
                    value: ""
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.9.0
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: TARGET_PODS
                    value: ""
                  - name: CONTAINER_RUNTIME
                    value: docker
                  - name: SOCKET_PATH
                    value: /var/run/docker.sock
                  - name: SEQUENCE
                    value: parallel
                  - name: TARGET_HOSTNAMES
                    value: ""
                  - name: MATCH_SCHEME
                    value: exact
                labels:
                  experiment: pod-dns-error
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/runtime-api-usage: "true"
                  app.kubernetes.io/version: 2.9.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-dns-error-xzi.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.9.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-dns-error-xzi
        path: /tmp/chaosengine-pod-dns-error-xzi.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              generateName: pod-dns-error-xzi
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                instance_id: 6bdb7b19-bfbd-499e-b824-05c439c0c190
                context: pod-dns-error-xzi_litmus
                workflow_name: custom-chaos-workflow-1662705982
            spec:
              appinfo:
                appns: launch
                applabel: app.kubernetes.io/instance=launch
                appkind: deployment
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-dns-error
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "120"
                        - name: TARGET_HOSTNAMES
                          value: ""
                        - name: MATCH_SCHEME
                          value: exact
                        - name: CONTAINER_RUNTIME
                          value: containerd
                        - name: SOCKET_PATH
                          value: /var/run/containerd/containerd.sock
                        - name: PODS_AFFECTED_PERC
                          value: ""
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-dns-error-xzi
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (6bdb7b19-bfbd-499e-b824-05c439c0c190,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.9.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
